# following line is key to prevent an endless build/deploy cycle
# when travis commits to pages:
if: commit_message !~ ^Deploy.*
dist: xenial
env:
  global:
  - PERL5LIB=/usr/share/perl5
language: python
services:
  - docker
python:
  - '2.7'
branches:
  only:
    - master
before_install:
  - docker pull maj1/icdc:model-tool-perl
  - sudo apt-get install sed
  #
install:
  - pip install -r bento-mdf/validators/mdf-validate/reqs.txt
script:
  - pushd model-desc
  - pytest
  - cp -aR ../bento-mdf/drivers/Perl/make-model/lib lib
  - cp -aR ../bento-mdf/drivers/Perl/make-model/bin bin
  # run model-tool with pre-built perl - fast
  - docker run --rm -it -v "$PWD":/home/user -w /home/user maj1/icdc:model-tool-perl -Ilib bin/model-tool -g update-model.svg -T update-model.txt icdc-model.yml icdc-model-props.yml
  - echo repo $(git remote get-url origin) > update-info.txt
  - echo commit $(git log -1 --pretty=format:"%h") >> update-info.txt
  - cat update-info.txt
  - cat update-info.txt update-model.txt > x.txt
  - cp -f x.txt update-model.txt
  - cat update-model.txt
  - cp icdc-model.yml icdc-model-props.yml ../docs/model-desc
  - cp update-model.txt ../docs/model-desc/icdc-model.txt
  - sed -e '1,6d' update-model.svg > ../docs/model-desc/icdc-model.svg
  - rm -f update-model.svg update-info.txt update-model.txt
  - pushd ../docs
  - cat ./README.md.content > ./README.md
  - echo "<div id='graph' style='display:off;'>" >> ./README.md
  - cat ./model-desc/icdc-model.svg >> ./README.md
  - echo "</div>" >> ./README.md
  - popd
  - rm -rf lib bin
  - rm -rf __pycache__
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  keep_history: true
  verbose: true
  on:
    branch: master
