name: model-test-and-deploy
on:
  push:
    branches:
      - feat-gh-actions

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Validate MDF
        run: |
          echo $PWD
          pip install bento-mdf/validators/mdf-validate
          push model-desc
          test-mdf.py icdc-model.yml icdc-model-props.yml
        shell: bash
          
  
