name: Model Validate and Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop

jobs:
  validate-and-build:
    permissions:
        packages: read
        contents: write
    uses: CBIIT/bento-workflows/.github/workflows/model-test-and-deploy.yml@v2.1.2
    with:
      model_files: |
        icdc-model.yml icdc-model-props.yml
      model_prefix: icdc-model
      event_name: ${{ github.event_name }}
      
